apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customresources.csharp.com
spec:
  group: csharp.com
  versions: 
    - name: v1alpha1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cityName:
                  type: string
  names:
    kind: CResource
    plural: customresources
  scope: Namespaced
